-- Add requirements_json column to contracts table
ALTER TABLE contracts ADD COLUMN requirements_json TEXT;

-- Populate requirements for Wikelo contracts (extracted from game data 4.6.0-live)
UPDATE contracts SET requirements_json = '[{"item": "Caranite (Pure)", "item_id": "harvestable_mineral_1h_carinitepure", "quantity": 1}, {"item": "QRT Heavy Core Armor", "item_id": "qrt_specialist_heavy_core_01_01_01", "quantity": 1}, {"item": "QRT Heavy Helmet", "item_id": "qrt_specialist_heavy_helmet_01_01_01", "quantity": 1}, {"item": "QRT Heavy Legs", "item_id": "qrt_specialist_heavy_legs_01_01_01", "quantity": 1}, {"item": "QRT Heavy Arms", "item_id": "qrt_specialist_heavy_arms_01_01_01", "quantity": 1}]' WHERE contract_key = 'wikelo_thecollector_orbarm';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 15}, {"item": "ASD Server Blade", "item_id": "carryable_1h_sq_pyro_serverblade_5", "quantity": 4}, {"item": "Tevarin War Service Marker (Pristine)", "item_id": "carryable_1h_cy_medal_1_pristine_c", "quantity": 1}]' WHERE contract_key = 'wikelo_thecollector_vehicle_medium_scorpius';
UPDATE contracts SET requirements_json = '[{"item": "Caranite", "item_id": "harvestable_mineral_1h_carinite", "quantity": 30}, {"item": "ASD Reward (PWL Tier 1)", "item_id": "carryable_tbo_asdreward_pwl1", "quantity": 4}, {"item": "ASD Reward (PWL Tier 2)", "item_id": "carryable_tbo_asdreward_pwl2", "quantity": 4}, {"item": "ASD Reward (PWL Tier 3)", "item_id": "carryable_tbo_asdreward_pwl3", "quantity": 4}, {"item": "Greycat Medium Arms", "item_id": "grin_utility_medium_arms_02_01_01", "quantity": 1}, {"item": "Greycat Medium Legs", "item_id": "grin_utility_medium_legs_02_01_01", "quantity": 1}, {"item": "FTA Medium Helmet", "item_id": "fta_medium_helmet_01_01_05", "quantity": 1}, {"item": "Greycat Medium Backpack", "item_id": "grin_utility_medium_backpack_02_01_01", "quantity": 1}, {"item": "Greycat Medium Core", "item_id": "grin_utility_medium_core_02_01_01", "quantity": 1}]' WHERE contract_key = 'wikelo_thecollector_nov_molten';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 40}, {"item": "Caranite (Pure)", "item_id": "harvestable_mineral_1h_carinitepure", "quantity": 4}, {"item": "Irradiated Valakkar Pearl (AAA)", "item_id": "carryable_2h_fl_vlk_pearl_irradiated_super_01", "quantity": 4}, {"item": "Tevarin War Service Marker (Pristine)", "item_id": "carryable_1h_cy_medal_1_pristine_c", "quantity": 4}]' WHERE contract_key = 'wikelo_thecollector_vehicle_large_f8c_milt';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 15}, {"item": "ASD Server Blade", "item_id": "carryable_1h_sq_pyro_serverblade_5", "quantity": 4}, {"item": "Ace Interceptor Helmet", "item_id": "basl_combat_light_helmet_02_01_01", "quantity": 3}, {"item": "Govt Cartography Medal (Pristine)", "item_id": "carryable_1h_cy_medal_1_pristine_d", "quantity": 1}]' WHERE contract_key = 'wikelo_thecollector_vehicle_medium_firebird';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 3}, {"item": "Caranite (Pure)", "item_id": "harvestable_mineral_1h_carinitepure", "quantity": 1}]' WHERE contract_key = 'wikelo_thecollector_vehicle_small_fortune';
UPDATE contracts SET requirements_json = '[{"item": "Caranite", "item_id": "harvestable_mineral_1h_carinite", "quantity": 10}, {"item": "Saldynium (Ore)", "item_id": "harvestable_ore_1h_saldyniumore", "quantity": 15}, {"item": "Parallax Energy Assault Rifle", "item_id": "volt_rifle_energy_01", "quantity": 1}, {"item": "Tundra Kopion Horn", "item_id": "harvestable_trophy_1h_kopionhorn_tundra", "quantity": 20}, {"item": "Jaclium (Ore)", "item_id": "harvestable_ore_1h_jacliumore", "quantity": 20}]' WHERE contract_key = 'wikelo_thecollector_orbvolt_kopskull';
UPDATE contracts SET requirements_json = '[{"item": "Caranite", "item_id": "harvestable_mineral_1h_carinite", "quantity": 10}, {"item": "Saldynium (Ore)", "item_id": "harvestable_ore_1h_saldyniumore", "quantity": 15}, {"item": "Parallax Energy Assault Rifle", "item_id": "volt_rifle_energy_01", "quantity": 1}, {"item": "Irradiated Valakkar Fang (Juvenile)", "item_id": "harvestable_trophy_1h_vlkjuvenilefang_irradiated", "quantity": 20}, {"item": "Jaclium (Ore)", "item_id": "harvestable_ore_1h_jacliumore", "quantity": 20}]' WHERE contract_key = 'wikelo_thecollector_orbvolt_miltskull';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 2}, {"item": "ASD Secure Drive", "item_id": "fps_consumable_harddrive_delving_hardened_asd_red", "quantity": 15}]' WHERE contract_key = 'wikelo_thecollector_vehicle_small_drake_golem';
UPDATE contracts SET requirements_json = '[{"item": "Irradiated Valakkar Pearl (AA)", "item_id": "carryable_2h_fl_vlk_pearl_irradiated_high_02", "quantity": 15}, {"item": "Ace Interceptor Helmet", "item_id": "basl_combat_light_helmet_02_01_01", "quantity": 10}, {"item": "Tevarin War Service Marker (Pristine)", "item_id": "carryable_1h_cy_medal_1_pristine_c", "quantity": 1}, {"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 20}]', title = 'Guardian Mod' WHERE contract_key = 'wikelo_thecollector_vehicle_medium_guardian';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 25}, {"item": "Irradiated Valakkar Pearl (AA)", "item_id": "carryable_2h_fl_vlk_pearl_irradiated_high_02", "quantity": 15}, {"item": "ASD Server Blade", "item_id": "carryable_1h_sq_pyro_serverblade_5", "quantity": 15}, {"item": "UEE 6th Platoon Medal (Pristine)", "item_id": "carryable_1h_cy_medal_1_pristine_b", "quantity": 2}]' WHERE contract_key = 'wikelo_thecollector_vehicle_medium_guardianqi';
UPDATE contracts SET requirements_json = '[{"item": "ASD Secure Drive", "item_id": "fps_consumable_harddrive_delving_hardened_asd_red", "quantity": 4}, {"item": "Kappa Light Arms", "item_id": "kap_combat_light_arms_02_01_01", "quantity": 1}, {"item": "Kappa Light Core", "item_id": "kap_combat_light_core_02_01_01", "quantity": 1}, {"item": "Kappa Light Helmet", "item_id": "kap_combat_light_helmet_02_01_01", "quantity": 1}, {"item": "Kappa Light Legs", "item_id": "kap_combat_light_legs_02_01_01", "quantity": 1}, {"item": "CDS Light Backpack", "item_id": "cds_combat_light_backpack_01_03_01", "quantity": 1}]' WHERE contract_key = 'wikelo_thecollector_ad_hush';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 2}, {"item": "Irradiated Valakkar Fang (Apex)", "item_id": "carryable_tbo_creature_trophy_vlkapexfang_irradiated", "quantity": 5}, {"item": "ARGO ATLS", "item_id": "argo_atls", "quantity": 1}, {"item": "NN-13 Neutron Cannon", "item_id": "mxox_neutroncannon_s1", "quantity": 2}]' WHERE contract_key = 'wikelo_thecollector_vehicle_ground_atls_ikti';
UPDATE contracts SET requirements_json = '[{"item": "Irradiated Valakkar Fang (Adult)", "item_id": "harvestable_trophy_1h_vlkadultfang_irradiated", "quantity": 10}, {"item": "Irradiated Valakkar Fang (Juvenile)", "item_id": "harvestable_trophy_1h_vlkjuvenilefang_irradiated", "quantity": 5}, {"item": "Volt Shotgun", "item_id": "volt_shotgun_energy_01", "quantity": 1}]' WHERE contract_key = 'wikelo_thecollector_ao_voltthwack';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 4}, {"item": "Saldynium (Ore)", "item_id": "harvestable_ore_1h_saldyniumore", "quantity": 20}, {"item": "Jaclium (Ore)", "item_id": "harvestable_ore_1h_jacliumore", "quantity": 20}]' WHERE contract_key = 'wikelo_thecollector_vehicle_ground_ursa_medical';
UPDATE contracts SET requirements_json = '[{"item": "QRT Heavy Core Armor", "item_id": "qrt_specialist_heavy_core_01_01_01", "quantity": 1}, {"item": "QRT Heavy Helmet", "item_id": "qrt_specialist_heavy_helmet_01_01_01", "quantity": 1}, {"item": "QRT Heavy Arms", "item_id": "qrt_specialist_heavy_arms_01_01_01", "quantity": 1}, {"item": "QRT Heavy Legs", "item_id": "qrt_specialist_heavy_legs_01_01_01", "quantity": 1}, {"item": "Irradiated Valakkar Pearl (AAA)", "item_id": "carryable_2h_fl_vlk_pearl_irradiated_super_01", "quantity": 1}]' WHERE contract_key = 'wikelo_thecollector_ao_irrarm';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 1}, {"item": "ARGO ATLS (Geo)", "item_id": "argo_atls_geo", "quantity": 1}, {"item": "NN-13 Neutron Cannon", "item_id": "mxox_neutroncannon_s1", "quantity": 2}, {"item": "ARGO ATLS (Ikti)", "item_id": "argo_atls_ikti", "quantity": 1}]' WHERE contract_key = 'wikelo_thecollector_vehicle_ground_atls_ikti_geo';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 30}, {"item": "Ace Interceptor Helmet", "item_id": "basl_combat_light_helmet_02_01_01", "quantity": 10}, {"item": "Caranite (Pure)", "item_id": "harvestable_mineral_1h_carinitepure", "quantity": 3}, {"item": "Irradiated Valakkar Pearl (AAA)", "item_id": "carryable_2h_fl_vlk_pearl_irradiated_super_01", "quantity": 3}]', title = 'Starlancer MAX Mod' WHERE contract_key = 'wikelo_thecollector_vehicle_large_starlancer_max';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 50}, {"item": "Ace Interceptor Helmet", "item_id": "basl_combat_light_helmet_02_01_01", "quantity": 15}, {"item": "ASD Secure Drive", "item_id": "fps_consumable_harddrive_delving_hardened_asd_red", "quantity": 30}, {"item": "Irradiated Valakkar Pearl (AAA)", "item_id": "carryable_2h_fl_vlk_pearl_irradiated_super_01", "quantity": 3}, {"item": "Tevarin War Service Marker (Pristine)", "item_id": "carryable_1h_cy_medal_1_pristine_c", "quantity": 3}, {"item": "ASD Server Blade", "item_id": "carryable_1h_sq_pyro_serverblade_5", "quantity": 3}, {"item": "Caranite (Pure)", "item_id": "harvestable_mineral_1h_carinitepure", "quantity": 3}]', title = 'Starlancer TAC Mod' WHERE contract_key = 'wikelo_thecollector_vehicle_large_starlancer_tac';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 50}, {"item": "Polaris Bit", "item_id": "carryable_1h_cy_banu_favour_wikelo_special", "quantity": 15}, {"item": "ASD Server Blade", "item_id": "carryable_1h_sq_pyro_serverblade_5", "quantity": 10}, {"item": "Caranite", "item_id": "harvestable_mineral_1h_carinite", "quantity": 20}, {"item": "Irradiated Valakkar Fang (Apex)", "item_id": "carryable_tbo_creature_trophy_vlkapexfang_irradiated", "quantity": 20}, {"item": "MG Scrip", "item_id": "carryable_1h_cy_physical_currency_scrip_merc_1", "quantity": 20}, {"item": "Ace Interceptor Helmet", "item_id": "basl_combat_light_helmet_02_01_01", "quantity": 15}, {"item": "Irradiated Valakkar Pearl (AAA)", "item_id": "carryable_2h_fl_vlk_pearl_irradiated_super_01", "quantity": 15}, {"item": "UEE 6th Platoon Medal (Pristine)", "item_id": "carryable_1h_cy_medal_1_pristine_b", "quantity": 15}, {"item": "Caranite (Pure)", "item_id": "harvestable_mineral_1h_carinitepure", "quantity": 15}, {"item": "ASD Secure Drive", "item_id": "fps_consumable_harddrive_delving_hardened_asd_red", "quantity": 15}, {"item": "ASD Reward (PWL Tier 1)", "item_id": "carryable_tbo_asdreward_pwl1", "quantity": 1}, {"item": "ASD Reward (PWL Tier 2)", "item_id": "carryable_tbo_asdreward_pwl2", "quantity": 1}, {"item": "ASD Reward (PWL Tier 3)", "item_id": "carryable_tbo_asdreward_pwl3", "quantity": 1}, {"item": "ASD Reward (RGL Tier 1)", "item_id": "carryable_tbo_asdreward_rgl1", "quantity": 1}, {"item": "ASD Reward (RGL Tier 2)", "item_id": "carryable_tbo_asdreward_rgl2", "quantity": 1}, {"item": "ASD Reward (RGL Tier 3)", "item_id": "carryable_tbo_asdreward_rgl3", "quantity": 1}, {"item": "ASD Reward (XTL Tier 1)", "item_id": "carryable_tbo_asdreward_xtl1", "quantity": 1}, {"item": "ASD Reward (XTL Tier 2)", "item_id": "carryable_tbo_asdreward_xtl2", "quantity": 1}, {"item": "ASD Reward (XTL Tier 3)", "item_id": "carryable_tbo_asdreward_xtl3", "quantity": 1}]' WHERE contract_key = 'wikelo_thecollector_vehicle_polaris';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 4}]' WHERE contract_key = 'wikelo_thecollector_vehicle_ground_nox';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 4}, {"item": "ASD Server Blade", "item_id": "carryable_1h_sq_pyro_serverblade_5", "quantity": 1}]', title = 'Peregrine Speed Mod' WHERE contract_key = 'wikelo_thecollector_vehicle_medium_peregrine';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 4}]' WHERE contract_key = 'wikelo_thecollector_vehicle_ground_pulse';
UPDATE contracts SET requirements_json = '[{"item": "OMC Heavy Core", "item_id": "omc_utility_heavy_core_01_01_16", "quantity": 1}, {"item": "OMC Heavy Arms", "item_id": "omc_utility_heavy_arms_01_01_16", "quantity": 1}, {"item": "OMC Heavy Legs", "item_id": "omc_utility_heavy_legs_01_01_16", "quantity": 1}, {"item": "CLDA Heavy Backpack", "item_id": "clda_env_heavy_backpack_01_02_16", "quantity": 1}, {"item": "ASD Secure Drive", "item_id": "fps_consumable_harddrive_delving_hardened_asd_red", "quantity": 10}, {"item": "ASD Reward (RGL Tier 1)", "item_id": "carryable_tbo_asdreward_rgl1", "quantity": 5}, {"item": "ASD Reward (RGL Tier 2)", "item_id": "carryable_tbo_asdreward_rgl2", "quantity": 5}, {"item": "ASD Reward (RGL Tier 3)", "item_id": "carryable_tbo_asdreward_rgl3", "quantity": 5}, {"item": "OMC Heavy Helmet", "item_id": "omc_utility_heavy_helmet_01_01_16", "quantity": 1}]' WHERE contract_key = 'wikelo_thecollector_nov_heavyutil';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 40}, {"item": "ASD Server Blade", "item_id": "carryable_1h_sq_pyro_serverblade_5", "quantity": 15}, {"item": "Caranite (Pure)", "item_id": "harvestable_mineral_1h_carinitepure", "quantity": 3}, {"item": "Irradiated Valakkar Pearl (AAA)", "item_id": "carryable_2h_fl_vlk_pearl_irradiated_super_01", "quantity": 3}]' WHERE contract_key = 'wikelo_thecollector_vehicle_large_f8c_stealth';
UPDATE contracts SET requirements_json = '[{"item": "ASD Secure Drive", "item_id": "fps_consumable_harddrive_delving_hardened_asd_red", "quantity": 7}, {"item": "Volt Sniper", "item_id": "volt_sniper_energy_01", "quantity": 1}]' WHERE contract_key = 'wikelo_thecollector_ad_zapzip';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 8}, {"item": "Tevarin War Service Marker (Pristine)", "item_id": "carryable_1h_cy_medal_1_pristine_c", "quantity": 1}]', title = 'Spirit C1 Mod' WHERE contract_key = 'wikelo_thecollector_vehicle_medium_spirit_c1';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 1}, {"item": "ARGO ATLS", "item_id": "argo_atls", "quantity": 1}]', title = 'ATLS Orange Line' WHERE contract_key = 'wikelo_thecolllector_vehicle_ground_atls_orangengrey';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 1}, {"item": "Caranite (Pure)", "item_id": "harvestable_mineral_1h_carinitepure", "quantity": 1}, {"item": "ARGO ATLS", "item_id": "argo_atls", "quantity": 1}]', title = 'ATLS Cool Metal Color' WHERE contract_key = 'wikelo_thecolllector_vehicle_ground_atls_rednblue';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 1}, {"item": "Irradiated Valakkar Pearl (AAA)", "item_id": "carryable_2h_fl_vlk_pearl_irradiated_super_01", "quantity": 1}, {"item": "ARGO ATLS", "item_id": "argo_atls", "quantity": 1}]', title = 'ATLS Snowland Color' WHERE contract_key = 'wikelo_thecolllector_vehicle_ground_atls_whitengreen';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 3}, {"item": "Govt Cartography Medal (Pristine)", "item_id": "carryable_1h_cy_medal_1_pristine_d", "quantity": 1}]' WHERE contract_key = 'wikelo_thecollector_vehicle_small_intrepid';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 30}, {"item": "Caranite (Pure)", "item_id": "harvestable_mineral_1h_carinitepure", "quantity": 3}, {"item": "Irradiated Valakkar Pearl (AAA)", "item_id": "carryable_2h_fl_vlk_pearl_irradiated_super_01", "quantity": 3}, {"item": "Govt Cartography Medal (Pristine)", "item_id": "carryable_1h_cy_medal_1_pristine_d", "quantity": 3}]' WHERE contract_key = 'wikelo_thecollector_vehicle_large_connie_tau';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 15}, {"item": "ASD Secure Drive", "item_id": "fps_consumable_harddrive_delving_hardened_asd_red", "quantity": 10}, {"item": "Tevarin War Service Marker (Pristine)", "item_id": "carryable_1h_cy_medal_1_pristine_c", "quantity": 1}]', title = 'Terrapin Medic Mod' WHERE contract_key = 'wikelo_thecollector_vehicle_medium_terrapin_medic';
UPDATE contracts SET requirements_json = '[{"item": "Vestal Water", "item_id": "drink_bottle_vestal_01_a", "quantity": 1}, {"item": "Tundra Kopion Horn", "item_id": "harvestable_trophy_1h_kopionhorn_tundra", "quantity": 3}]' WHERE contract_key = 'wikelo_thecollector_intro';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 16}, {"item": "ASD Server Blade", "item_id": "carryable_1h_sq_pyro_serverblade_5", "quantity": 3}, {"item": "Ace Interceptor Helmet", "item_id": "basl_combat_light_helmet_02_01_01", "quantity": 5}, {"item": "Govt Cartography Medal (Pristine)", "item_id": "carryable_1h_cy_medal_1_pristine_d", "quantity": 1}]' WHERE contract_key = 'wikelo_thecollector_vehicle_medium_f7_mk2';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 20}, {"item": "Caranite", "item_id": "harvestable_mineral_1h_carinite", "quantity": 15}, {"item": "Ace Interceptor Helmet", "item_id": "basl_combat_light_helmet_02_01_01", "quantity": 10}, {"item": "Caranite (Pure)", "item_id": "harvestable_mineral_1h_carinitepure", "quantity": 2}]', title = 'Zeus CL Mod' WHERE contract_key = 'wikelo_thecollector_vehicle_medium_zeuscl';
UPDATE contracts SET requirements_json = '[{"item": "Wikelo Favor", "item_id": "carryable_1h_cy_banu_favour_wikelo", "quantity": 10}, {"item": "UEE 6th Platoon Medal (Pristine)", "item_id": "carryable_1h_cy_medal_1_pristine_b", "quantity": 1}]', title = 'Zeus ES Mod' WHERE contract_key = 'wikelo_thecollector_vehicle_medium_zeuses';

-- Mark contracts using generic template (requirements are randomized in-game)
UPDATE contracts SET requirements_json = 'random' WHERE contract_key IN ('wikelo_thecollector_spikeyarmor', 'wikelo_thecollector_bigbooma', 'wikelo_thecollector_nonepistol', 'wikelo_thecollector_battle', 'wikelo_thecollector_slimylmg', 'wikelo_thecollector_foodorder', 'wikelo_thecollector_favours_irradiatedpearls', 'wikelo_thecollector_vehicle_large_anvil_asgard', 'wikelo_thecollector_vehicle_medium_guardianmx', 'wikelo_thecollector_vehicle_small_kruger_wolf_unique', 'wikelo_thecollector_vehicle_small_misc_prospector', 'wikelo_thecollector_vehicle_large_prowler_utility', 'wikelo_thecollector_vehicle_small_rsi_meteor', 'wikelo_thecollector_vehicle_small_argo_raft', 'wikelo_thecollector_vehicle_medium_starfighter_ion', 'wikelo_thecollector_vehicle_super_idris', 'wikelo_thecollector_vehicle_medium_starfighter_inferno', 'wikelo_thecollector_vehicle_large_crusader_a2', 'wikelo_thecollector_vehicle_small_kruger_wolf');
