-- Migration: Remove game_version_id from UNIQUE constraints
-- Generated by generate_unique_rebuild.py
--
-- Tables are dropped and recreated with corrected UNIQUE constraints.
-- Game-data tables contain no user data; pipeline will reload.

PRAGMA foreign_keys = OFF;

-- Rebuild: armor_resistance_profiles
DROP TABLE IF EXISTS armor_resistance_profiles;
CREATE TABLE armor_resistance_profiles (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid              TEXT    NOT NULL,
  name              TEXT    NOT NULL,
  slug              TEXT,
  physical          REAL,
  energy            REAL,
  distortion        REAL,
  thermal           REAL,
  biochemical       REAL,
  stun              REAL,
  impact_force      REAL,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT    DEFAULT (datetime('now')),
  updated_at        TEXT    DEFAULT (datetime('now')), removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);

-- Rebuild: commodities
DROP TABLE IF EXISTS commodities;
CREATE TABLE commodities (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid              TEXT    NOT NULL,
  name              TEXT    NOT NULL,
  slug              TEXT,
  class_name        TEXT,
  description       TEXT,
  category          TEXT    NOT NULL,
  sub_category      TEXT,
  occupancy_cscu    INTEGER,
  is_illegal        INTEGER DEFAULT 0,
  is_raw            INTEGER DEFAULT 0,
  is_boxable        INTEGER DEFAULT 0,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT    DEFAULT (datetime('now')),
  updated_at        TEXT    DEFAULT (datetime('now')), removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_commodities_category ON commodities(category);
CREATE INDEX idx_commodities_slug ON commodities(slug);

-- Rebuild: component_coolers
DROP TABLE IF EXISTS component_coolers;
CREATE TABLE component_coolers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  component_id INTEGER NOT NULL REFERENCES vehicle_components(id) ON DELETE CASCADE,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  cooling_rate REAL,
  max_temperature REAL,
  overheat_temperature REAL, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(component_id)
);
CREATE INDEX idx_component_coolers_cid ON component_coolers(component_id);

-- Rebuild: component_mining
DROP TABLE IF EXISTS component_mining;
CREATE TABLE component_mining (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  component_id INTEGER NOT NULL REFERENCES vehicle_components(id) ON DELETE CASCADE,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  mining_throttle_speed REAL,
  min_calibration_requirement REAL,
  max_calibration_requirement REAL, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(component_id)
);
CREATE INDEX idx_component_mining_cid ON component_mining(component_id);

-- Rebuild: component_missiles
DROP TABLE IF EXISTS component_missiles;
CREATE TABLE component_missiles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  component_id INTEGER NOT NULL REFERENCES vehicle_components(id) ON DELETE CASCADE,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  ammo_count INTEGER,
  missile_type TEXT,
  lock_time REAL,
  tracking_signal TEXT,
  damage REAL,
  blast_radius REAL,
  speed REAL,
  lock_range REAL, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(component_id)
);
CREATE INDEX idx_component_missiles_cid ON component_missiles(component_id);

-- Rebuild: component_powerplants
DROP TABLE IF EXISTS component_powerplants;
CREATE TABLE component_powerplants (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  component_id INTEGER NOT NULL REFERENCES vehicle_components(id) ON DELETE CASCADE,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  power_output REAL,
  overpower_performance REAL,
  overclock_performance REAL,
  overclock_threshold_min REAL,
  overclock_threshold_max REAL, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(component_id)
);
CREATE INDEX idx_component_powerplants_cid ON component_powerplants(component_id);

-- Rebuild: component_qed
DROP TABLE IF EXISTS component_qed;
CREATE TABLE component_qed (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  component_id INTEGER NOT NULL REFERENCES vehicle_components(id) ON DELETE CASCADE,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  qed_range REAL,
  qed_strength REAL, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(component_id)
);
CREATE INDEX idx_component_qed_cid ON component_qed(component_id);

-- Rebuild: component_quantum_drives
DROP TABLE IF EXISTS component_quantum_drives;
CREATE TABLE component_quantum_drives (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  component_id INTEGER NOT NULL REFERENCES vehicle_components(id) ON DELETE CASCADE,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  quantum_speed REAL,
  quantum_range REAL,
  fuel_rate REAL,
  spool_time REAL,
  cooldown_time REAL,
  stage1_accel REAL,
  stage2_accel REAL,
  calibration_rate REAL,
  engage_speed REAL, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(component_id)
);
CREATE INDEX idx_component_quantum_drives_cid ON component_quantum_drives(component_id);

-- Rebuild: component_radar
DROP TABLE IF EXISTS component_radar;
CREATE TABLE component_radar (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  component_id INTEGER NOT NULL REFERENCES vehicle_components(id) ON DELETE CASCADE,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  radar_range REAL,
  radar_angle REAL, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(component_id)
);
CREATE INDEX idx_component_radar_cid ON component_radar(component_id);

-- Rebuild: component_shields
DROP TABLE IF EXISTS component_shields;
CREATE TABLE component_shields (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  component_id INTEGER NOT NULL REFERENCES vehicle_components(id) ON DELETE CASCADE,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  shield_hp REAL,
  shield_regen REAL,
  resist_physical REAL,
  resist_energy REAL,
  resist_distortion REAL,
  resist_thermal REAL,
  regen_delay REAL,
  downed_regen_delay REAL,
  resist_physical_min REAL,
  resist_energy_min REAL,
  resist_distortion_min REAL,
  resist_thermal_min REAL,
  absorb_physical_min REAL,
  absorb_physical_max REAL, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(component_id)
);
CREATE INDEX idx_component_shields_cid ON component_shields(component_id);

-- Rebuild: component_thrusters
DROP TABLE IF EXISTS component_thrusters;
CREATE TABLE component_thrusters (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  component_id INTEGER NOT NULL REFERENCES vehicle_components(id) ON DELETE CASCADE,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  thrust_force REAL,
  fuel_burn_rate REAL, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(component_id)
);
CREATE INDEX idx_component_thrusters_cid ON component_thrusters(component_id);

-- Rebuild: component_turrets
DROP TABLE IF EXISTS component_turrets;
CREATE TABLE component_turrets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  component_id INTEGER NOT NULL REFERENCES vehicle_components(id) ON DELETE CASCADE,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  rotation_speed REAL,
  min_pitch REAL,
  max_pitch REAL,
  min_yaw REAL,
  max_yaw REAL,
  gimbal_type TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(component_id)
);
CREATE INDEX idx_component_turrets_cid ON component_turrets(component_id);

-- Rebuild: component_weapons
DROP TABLE IF EXISTS component_weapons;
CREATE TABLE component_weapons (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  component_id INTEGER NOT NULL REFERENCES vehicle_components(id) ON DELETE CASCADE,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  rounds_per_minute REAL,
  ammo_container_size INTEGER,
  damage_per_shot REAL,
  damage_type TEXT,
  projectile_speed REAL,
  effective_range REAL,
  dps REAL,
  heat_per_shot REAL,
  fire_modes TEXT,
  damage_physical REAL,
  damage_energy REAL,
  damage_distortion REAL,
  damage_thermal REAL,
  penetration REAL,
  weapon_range REAL,
  laser_instability REAL,
  optimal_charge_window_size REAL,
  resistance_modifier REAL,
  shatter_damage_modifier REAL,
  optimal_charge_rate REAL,
  catastrophic_charge_rate REAL,
  filter_modifier REAL,
  charge_time REAL,
  decay_ratio REAL,
  interdiction_effect_time REAL, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(component_id)
);
CREATE INDEX idx_component_weapons_cid ON component_weapons(component_id);

-- Rebuild: consumable_effect_types
DROP TABLE IF EXISTS consumable_effect_types;
CREATE TABLE "consumable_effect_types" (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  key         TEXT    NOT NULL,
  name        TEXT    NOT NULL,
  description TEXT,
  is_positive INTEGER DEFAULT 1,
  game_version_id INTEGER REFERENCES game_versions(id), data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(key)
);

-- Rebuild: consumable_effects
DROP TABLE IF EXISTS consumable_effects;
CREATE TABLE consumable_effects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  consumable_uuid TEXT NOT NULL,
  effect_key TEXT NOT NULL,
  magnitude REAL,
  duration_seconds REAL,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id), removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(consumable_uuid, effect_key)
);
CREATE INDEX idx_consumable_effects_uuid ON consumable_effects(consumable_uuid);
CREATE INDEX idx_consumable_effects_version ON consumable_effects(game_version_id);

-- Rebuild: consumables
DROP TABLE IF EXISTS consumables;
CREATE TABLE consumables (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid            TEXT    NOT NULL,
  class_name      TEXT    NOT NULL,
  name            TEXT    NOT NULL,
  slug            TEXT,
  description     TEXT,
  type            TEXT,
  sub_type        TEXT,
  manufacturer_id INTEGER REFERENCES manufacturers(id),
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  created_at      TEXT    DEFAULT (datetime('now')),
  updated_at      TEXT    DEFAULT (datetime('now')), removed INTEGER NOT NULL DEFAULT 0, [can_loot] INTEGER, [grade] INTEGER, [grid_height] INTEGER, [grid_width] INTEGER, [inventory_volume] REAL, [loot_rarity] TEXT, [manufacturer_code] TEXT, [size] INTEGER, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_consumables_slug     ON consumables(slug);
CREATE INDEX idx_consumables_sub_type ON consumables(sub_type);
CREATE INDEX idx_consumables_type     ON consumables(type);

-- Index rebuild: contract_generator_blueprint_pools
DROP INDEX IF EXISTS idx_cgbp_upsert;
CREATE UNIQUE INDEX idx_cgbp_upsert
  ON contract_generator_blueprint_pools(contract_generator_contract_id, crafting_blueprint_reward_pool_id);

-- Index rebuild: contract_generator_careers
DROP INDEX IF EXISTS idx_cgc_upsert;
CREATE UNIQUE INDEX idx_cgc_upsert
  ON contract_generator_careers(debug_name, contract_generator_id);

-- Rebuild: contract_generator_contracts
DROP TABLE IF EXISTS contract_generator_contracts;
CREATE TABLE contract_generator_contracts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  career_id INTEGER NOT NULL REFERENCES contract_generator_careers(id),
  uuid TEXT NOT NULL,
  debug_name TEXT NOT NULL,
  difficulty TEXT,
  template TEXT,
  min_standing TEXT,
  max_standing TEXT,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id), rep_reward INTEGER, rep_rewards_json TEXT, title_loc_key TEXT, desc_loc_key TEXT, item_rewards_json TEXT, completion_tags_json TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_cgc_career_id ON contract_generator_contracts(career_id);
CREATE INDEX idx_cgc_desc_loc_key ON contract_generator_contracts(desc_loc_key);

-- Rebuild: contract_generators
DROP TABLE IF EXISTS contract_generators;
CREATE TABLE contract_generators (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  generator_key TEXT NOT NULL,
  display_name TEXT,
  faction_name TEXT,
  guild TEXT,
  mission_type TEXT,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id), description TEXT, focus TEXT, headquarters TEXT, leadership TEXT, faction_slug TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(generator_key)
);
CREATE INDEX idx_cg_faction_slug ON contract_generators(faction_slug, game_version_id);
CREATE INDEX idx_cg_generator_key ON contract_generators(generator_key);

-- Rebuild: contracts
DROP TABLE IF EXISTS contracts;
CREATE TABLE contracts (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  contract_key     TEXT    NOT NULL,
  giver            TEXT    NOT NULL,
  giver_slug       TEXT    NOT NULL,
  category         TEXT    NOT NULL,
  sequence_num     INTEGER,
  title            TEXT    NOT NULL,
  description      TEXT,
  reward_text      TEXT,
  reward_amount    INTEGER DEFAULT 0,
  reward_currency  TEXT,
  is_dynamic_reward INTEGER DEFAULT 0,
  is_active        INTEGER DEFAULT 1,
  notes            TEXT,
  game_version_id  INTEGER NOT NULL REFERENCES game_versions(id), requirements_json TEXT, removed INTEGER NOT NULL DEFAULT 0, reward_vehicle_slug TEXT, [name] TEXT, [slug] TEXT, [uuid] TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(contract_key)
);
CREATE INDEX idx_contracts_giver_slug ON contracts(giver_slug);
CREATE INDEX idx_contracts_is_active  ON contracts(is_active);

-- Rebuild: crafting_blueprint_reward_pools
DROP TABLE IF EXISTS crafting_blueprint_reward_pools;
CREATE TABLE crafting_blueprint_reward_pools (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    key TEXT NOT NULL,
    name TEXT,
    game_version_id INTEGER REFERENCES game_versions(id), data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
    UNIQUE(key)
);
CREATE INDEX idx_crafting_bp_reward_pools_version ON crafting_blueprint_reward_pools(game_version_id);

-- Rebuild: damage_types
DROP TABLE IF EXISTS damage_types;
CREATE TABLE damage_types (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid            TEXT    NOT NULL,
  name            TEXT    NOT NULL,
  slug            TEXT,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id), removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);

-- Rebuild: faction_reputation_scopes
DROP TABLE IF EXISTS faction_reputation_scopes;
CREATE TABLE faction_reputation_scopes (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  faction_id        INTEGER NOT NULL REFERENCES factions(id),
  reputation_scope_id INTEGER NOT NULL REFERENCES reputation_scopes(id),
  is_primary        INTEGER DEFAULT 0,
  source            TEXT,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT    DEFAULT (datetime('now')), data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(faction_id, reputation_scope_id)
);
CREATE INDEX idx_faction_reputation_scopes_faction ON faction_reputation_scopes(faction_id);
CREATE INDEX idx_faction_reputation_scopes_scope ON faction_reputation_scopes(reputation_scope_id);
CREATE INDEX idx_faction_reputation_scopes_version ON faction_reputation_scopes(game_version_id);

-- Rebuild: factions
DROP TABLE IF EXISTS factions;
CREATE TABLE factions (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid              TEXT    NOT NULL,
  name              TEXT    NOT NULL,
  slug              TEXT,
  description       TEXT,
  faction_type      TEXT,
  headquarters      TEXT,
  founded           TEXT,
  leadership        TEXT,
  area              TEXT,
  focus             TEXT,
  default_reaction  TEXT,
  can_arrest        INTEGER DEFAULT 0,
  polices_crime     INTEGER DEFAULT 0,
  no_legal_rights   INTEGER DEFAULT 0,
  allies_json       TEXT,
  enemies_json      TEXT,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT    DEFAULT (datetime('now')),
  updated_at        TEXT    DEFAULT (datetime('now')), removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_factions_slug ON factions(slug);
CREATE INDEX idx_factions_type ON factions(faction_type);

-- Rebuild: fps_ammo
DROP TABLE IF EXISTS fps_ammo;
CREATE TABLE fps_ammo (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid            TEXT    NOT NULL,
    name            TEXT    NOT NULL,
    slug            TEXT,
    class_name      TEXT,
    manufacturer_id INTEGER REFERENCES manufacturers(id),
    sub_type        TEXT,
    description     TEXT,
    game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
    raw_data        TEXT,
    created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME DEFAULT CURRENT_TIMESTAMP, removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
    UNIQUE(uuid)
);

-- Rebuild: fps_ammo_types
DROP TABLE IF EXISTS fps_ammo_types;
CREATE TABLE fps_ammo_types (
  id                 INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid               TEXT NOT NULL,
  name               TEXT NOT NULL,
  display_name       TEXT,
  slug               TEXT,
  class_name         TEXT,
  caliber            TEXT,
  damage_per_round   REAL,
  damage_type        TEXT,
  projectile_speed   REAL,
  magazine_capacity  INTEGER,
  game_version_id    INTEGER NOT NULL REFERENCES game_versions(id),
  created_at         TEXT DEFAULT (datetime('now')), manufacturer_id INTEGER REFERENCES manufacturers(id), removed INTEGER NOT NULL DEFAULT 0, [ammo_type] TEXT, [damage_distortion] REAL, [damage_energy] REAL, [damage_physical] REAL, [speed] REAL, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_fps_ammo_types_version ON fps_ammo_types(game_version_id);

-- Rebuild: fps_armour
DROP TABLE IF EXISTS fps_armour;
CREATE TABLE fps_armour (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid            TEXT    NOT NULL,
  name            TEXT    NOT NULL,
  slug            TEXT,
  class_name      TEXT,
  manufacturer_id INTEGER REFERENCES manufacturers(id),
  sub_type        TEXT,
  size            INTEGER,
  grade           TEXT,
  description     TEXT,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  raw_data        TEXT,
  created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME DEFAULT CURRENT_TIMESTAMP, resist_physical REAL, resist_energy REAL, resist_distortion REAL, resist_thermal REAL, resist_biochemical REAL, resist_stun REAL, ir_emission REAL, em_emission REAL, item_port_count INTEGER, removed INTEGER NOT NULL DEFAULT 0, [can_loot] INTEGER, [grid_height] INTEGER, [grid_width] INTEGER, [inventory_volume] REAL, [loot_rarity] TEXT, [manufacturer_code] TEXT, [radiation_capacity] REAL, [radiation_dissipation] REAL, [temperature_max] REAL, [temperature_min] REAL, data_source TEXT, protected_body_parts TEXT, armor_weight TEXT, integrity_threshold REAL, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);

-- Rebuild: fps_attachments
DROP TABLE IF EXISTS fps_attachments;
CREATE TABLE fps_attachments (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid            TEXT    NOT NULL,
  name            TEXT    NOT NULL,
  slug            TEXT,
  class_name      TEXT,
  manufacturer_id INTEGER REFERENCES manufacturers(id),
  sub_type        TEXT,
  size            INTEGER,
  description     TEXT,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  raw_data        TEXT,
  created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME DEFAULT CURRENT_TIMESTAMP, zoom_scale REAL, second_zoom_scale REAL, damage_multiplier REAL, sound_radius_multiplier REAL, scope_type TEXT, zeroing_range REAL, zeroing_increment REAL, auto_zeroing_time REAL, is_low_light INTEGER DEFAULT 0, recoil_decay REAL, recoil_strength REAL, recoil_randomness REAL, spread_min REAL, spread_max REAL, spread_attack_time REAL, spread_decay_time REAL, light_type TEXT, light_color TEXT, light_intensity REAL, light_radius REAL, light_fov REAL, removed INTEGER NOT NULL DEFAULT 0, [can_loot] INTEGER, [grade] INTEGER, [grid_height] INTEGER, [grid_width] INTEGER, [inventory_volume] REAL, [loot_rarity] TEXT, [magazine_capacity] INTEGER, [magazine_restock_count] INTEGER, [manufacturer_code] TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);

-- Rebuild: fps_carryables
DROP TABLE IF EXISTS fps_carryables;
CREATE TABLE fps_carryables (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid              TEXT NOT NULL,
  name              TEXT NOT NULL,
  display_name      TEXT,
  slug              TEXT,
  class_name        TEXT,
  sub_type          TEXT,
  mass              REAL,
  interaction_type  TEXT,
  value             REAL,
  description       TEXT,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT DEFAULT (datetime('now')), removed INTEGER NOT NULL DEFAULT 0, [can_loot] INTEGER, [grade] INTEGER, [grid_height] INTEGER, [grid_width] INTEGER, [inventory_volume] REAL, [loot_rarity] TEXT, [manufacturer_code] TEXT, [size] INTEGER, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_fps_carryables_version ON fps_carryables(game_version_id);

-- Rebuild: fps_clothing
DROP TABLE IF EXISTS fps_clothing;
CREATE TABLE fps_clothing (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid            TEXT    NOT NULL,
  class_name      TEXT    NOT NULL,
  name            TEXT    NOT NULL,
  slug            TEXT,
  description     TEXT,
  slot            TEXT,
  size            REAL,
  grade           TEXT,
  manufacturer_id INTEGER REFERENCES manufacturers(id),
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  created_at      TEXT    DEFAULT (datetime('now')),
  updated_at      TEXT    DEFAULT (datetime('now')), resist_physical REAL, resist_energy REAL, resist_distortion REAL, resist_thermal REAL, resist_biochemical REAL, resist_stun REAL, ir_emission REAL, em_emission REAL, storage_capacity INTEGER, temperature_range_min REAL, temperature_range_max REAL, removed INTEGER NOT NULL DEFAULT 0, sub_type TEXT, [can_loot] INTEGER, [grid_height] INTEGER, [grid_width] INTEGER, [inventory_volume] REAL, [item_port_count] INTEGER, [loot_rarity] TEXT, [manufacturer_code] TEXT, [radiation_capacity] REAL, [radiation_dissipation] REAL, [temperature_max] REAL, [temperature_min] REAL, data_source TEXT, protected_body_parts TEXT, armor_weight TEXT, integrity_threshold REAL, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_fps_clothing_slot ON fps_clothing(slot);
CREATE INDEX idx_fps_clothing_slug ON fps_clothing(slug);

-- Rebuild: fps_helmets
DROP TABLE IF EXISTS fps_helmets;
CREATE TABLE fps_helmets (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid            TEXT    NOT NULL,
  class_name      TEXT    NOT NULL,
  name            TEXT    NOT NULL,
  slug            TEXT,
  description     TEXT,
  sub_type        TEXT,
  size            REAL,
  grade           TEXT,
  manufacturer_id INTEGER REFERENCES manufacturers(id),
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  created_at      TEXT    DEFAULT (datetime('now')),
  updated_at      TEXT    DEFAULT (datetime('now')), resist_physical REAL, resist_energy REAL, resist_distortion REAL, resist_thermal REAL, resist_biochemical REAL, resist_stun REAL, ir_emission REAL, em_emission REAL, item_port_count INTEGER, atmosphere_capacity REAL, removed INTEGER NOT NULL DEFAULT 0, [can_loot] INTEGER, [grid_height] INTEGER, [grid_width] INTEGER, [has_visor_display] INTEGER, [inventory_volume] REAL, [loot_rarity] TEXT, [manufacturer_code] TEXT, [max_fov] REAL, [min_fov] REAL, [radiation_capacity] REAL, [radiation_dissipation] REAL, [temperature_max] REAL, [temperature_min] REAL, data_source TEXT, protected_body_parts TEXT, armor_weight TEXT, integrity_threshold REAL, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_fps_helmets_slug     ON fps_helmets(slug);
CREATE INDEX idx_fps_helmets_sub_type ON fps_helmets(sub_type);

-- Rebuild: fps_melee
DROP TABLE IF EXISTS fps_melee;
CREATE TABLE fps_melee (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid              TEXT NOT NULL,
  name              TEXT NOT NULL,
  display_name      TEXT,
  slug              TEXT,
  class_name        TEXT,
  manufacturer_id   INTEGER REFERENCES manufacturers(id),
  sub_type          TEXT,
  size              INTEGER,
  description       TEXT,
  damage            REAL,
  damage_type       TEXT,
  attack_speed      REAL,
  range             REAL,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT DEFAULT (datetime('now')),
  updated_at        TEXT DEFAULT (datetime('now')), heavy_damage REAL, attack_types REAL, can_block INTEGER, can_takedown INTEGER, removed INTEGER NOT NULL DEFAULT 0, [can_loot] INTEGER, [grade] INTEGER, [grid_height] INTEGER, [grid_width] INTEGER, [inventory_volume] REAL, [loot_rarity] TEXT, [manufacturer_code] TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_fps_melee_manufacturer ON fps_melee(manufacturer_id);
CREATE INDEX idx_fps_melee_version ON fps_melee(game_version_id);

-- Rebuild: fps_utilities
DROP TABLE IF EXISTS fps_utilities;
CREATE TABLE fps_utilities (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid            TEXT    NOT NULL,
  name            TEXT    NOT NULL,
  slug            TEXT,
  class_name      TEXT,
  manufacturer_id INTEGER REFERENCES manufacturers(id),
  sub_type        TEXT,
  description     TEXT,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  raw_data        TEXT,
  created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME DEFAULT CURRENT_TIMESTAMP, heal_amount REAL, effect_duration REAL, consumable_type TEXT, damage REAL, blast_radius REAL, fuse_time REAL, device_type TEXT, removed INTEGER NOT NULL DEFAULT 0, detonation_type TEXT, [can_loot] INTEGER, [grade] TEXT, [grid_height] INTEGER, [grid_width] INTEGER, [inventory_volume] REAL, [loot_rarity] TEXT, [manufacturer_code] TEXT, [size] INTEGER, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);

-- Rebuild: fps_weapons
DROP TABLE IF EXISTS fps_weapons;
CREATE TABLE fps_weapons (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid            TEXT    NOT NULL,
  name            TEXT    NOT NULL,
  slug            TEXT,
  class_name      TEXT,
  manufacturer_id INTEGER REFERENCES manufacturers(id),
  sub_type        TEXT,
  size            INTEGER,
  description     TEXT,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  raw_data        TEXT,
  created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME DEFAULT CURRENT_TIMESTAMP, rounds_per_minute REAL, fire_modes TEXT, burst_count INTEGER, ammo_capacity INTEGER, zoom_factor REAL, item_port_count INTEGER, damage REAL, damage_type TEXT, projectile_speed REAL, effective_range REAL, dps REAL, magazine_uuid TEXT, spread_min REAL, spread_max REAL, removed INTEGER NOT NULL DEFAULT 0, heat_per_shot REAL, charge_time REAL, recoil_strength REAL, weapon_class TEXT, [can_loot] INTEGER, [cooling_per_second] REAL, [grade] INTEGER, [grid_height] INTEGER, [grid_width] INTEGER, [heal_range] REAL, [heal_rate] REAL, [heal_sensor_range] REAL, [inventory_volume] REAL, [loot_rarity] TEXT, [manufacturer_code] TEXT, [mining_throttle_speed] REAL, [overheat_fix_time] REAL, [overheat_temperature] REAL, [projectile_lifetime] REAL, [time_to_cooling_starts] REAL, [tool_type] TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);

-- Rebuild: harvestables
DROP TABLE IF EXISTS harvestables;
CREATE TABLE harvestables (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid            TEXT    NOT NULL,
  class_name      TEXT    NOT NULL,
  name            TEXT    NOT NULL,
  slug            TEXT,
  description     TEXT,
  sub_type        TEXT,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  created_at      TEXT    DEFAULT (datetime('now')),
  updated_at      TEXT    DEFAULT (datetime('now')), removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_harvestables_slug ON harvestables(slug);

-- Rebuild: jurisdiction_infraction_overrides
DROP TABLE IF EXISTS jurisdiction_infraction_overrides;
CREATE TABLE jurisdiction_infraction_overrides (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  jurisdiction_id     INTEGER NOT NULL REFERENCES law_jurisdictions(id),
  infraction_id       INTEGER NOT NULL REFERENCES law_infractions(id),
  overrides_json      TEXT,
  game_version_id     INTEGER NOT NULL REFERENCES game_versions(id),
  created_at          TEXT    DEFAULT (datetime('now')),
  updated_at          TEXT    DEFAULT (datetime('now')), data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(jurisdiction_id, infraction_id)
);
CREATE INDEX idx_jio_infraction ON jurisdiction_infraction_overrides(infraction_id);
CREATE INDEX idx_jio_jurisdiction ON jurisdiction_infraction_overrides(jurisdiction_id);

-- Rebuild: law_infractions
DROP TABLE IF EXISTS law_infractions;
CREATE TABLE law_infractions (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid              TEXT    NOT NULL,
  name              TEXT    NOT NULL,
  slug              TEXT,
  description       TEXT,
  severity          TEXT    NOT NULL,
  triggers_json     TEXT,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT    DEFAULT (datetime('now')),
  updated_at        TEXT    DEFAULT (datetime('now')), is_felony INTEGER, grace_allowance REAL, grace_allowance_cooldown REAL, grace_period REAL, grace_cooloff_scale REAL, display_grace_time INTEGER, escalated_fine_multiplier REAL, early_payment_period REAL, lifetime REAL, cool_off_time REAL, press_charges_notification_time REAL, remove_time_seconds REAL, felony_merits REAL, ignore_party_member INTEGER, hide_crime_notification INTEGER, hide_crime_journal INTEGER, removed INTEGER NOT NULL DEFAULT 0, [cool_off_seconds] REAL, [escalation_multiplier] REAL, [fine_amount] REAL, [lifetime_hours] REAL, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_law_infractions_severity ON law_infractions(severity);
CREATE INDEX idx_law_infractions_slug ON law_infractions(slug);

-- Rebuild: law_jurisdictions
DROP TABLE IF EXISTS law_jurisdictions;
CREATE TABLE law_jurisdictions (
  id                    INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid                  TEXT    NOT NULL,
  name                  TEXT    NOT NULL,
  slug                  TEXT,
  parent_uuid           TEXT,
  respects_parent_laws  INTEGER DEFAULT 1,
  base_fine             INTEGER,
  is_prison             INTEGER DEFAULT 0,
  max_stolen_goods_scu  REAL,
  prohibited_goods_json TEXT,
  controlled_substances_json TEXT,
  game_version_id       INTEGER NOT NULL REFERENCES game_versions(id),
  created_at            TEXT    DEFAULT (datetime('now')),
  updated_at            TEXT    DEFAULT (datetime('now')), removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_law_jurisdictions_slug ON law_jurisdictions(slug);

-- Rebuild: loot_map
DROP TABLE IF EXISTS loot_map;
CREATE TABLE loot_map (
  id                   INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid                 TEXT    NOT NULL,
  name                 TEXT    NOT NULL,
  class_name           TEXT,
  type                 TEXT,
  sub_type             TEXT,
  rarity               TEXT,
  vehicle_component_id INTEGER REFERENCES vehicle_components(id),
  fps_weapon_id        INTEGER REFERENCES fps_weapons(id),
  fps_armour_id        INTEGER REFERENCES fps_armour(id),
  fps_attachment_id    INTEGER REFERENCES fps_attachments(id),
  fps_utility_id       INTEGER REFERENCES fps_utilities(id),
  fps_helmet_id        INTEGER REFERENCES fps_helmets(id),
  fps_clothing_id      INTEGER REFERENCES fps_clothing(id),
  consumable_id        INTEGER REFERENCES consumables(id),
  harvestable_id       INTEGER REFERENCES harvestables(id),
  props_id             INTEGER REFERENCES props(id),
  game_version_id      INTEGER NOT NULL REFERENCES game_versions(id),
  updated_at           TEXT    DEFAULT (datetime('now')), ship_missile_id INTEGER REFERENCES ship_missiles(id), manufacturer_name TEXT, category TEXT, removed INTEGER NOT NULL DEFAULT 0, fps_melee_id INTEGER REFERENCES fps_melee(id), fps_carryable_id INTEGER REFERENCES fps_carryables(id), [loot_rarity] TEXT, [slug] TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_loot_map_category ON loot_map(category);
CREATE INDEX idx_loot_map_class_name ON loot_map(class_name);
CREATE INDEX idx_loot_map_consumable   ON loot_map(consumable_id);
CREATE INDEX idx_loot_map_fps_armour_id ON loot_map(fps_armour_id);
CREATE INDEX idx_loot_map_fps_carryable ON loot_map(fps_carryable_id);
CREATE INDEX idx_loot_map_fps_clothing_id ON loot_map(fps_clothing_id);
CREATE INDEX idx_loot_map_fps_helmet_id ON loot_map(fps_helmet_id);
CREATE INDEX idx_loot_map_fps_melee ON loot_map(fps_melee_id);
CREATE INDEX idx_loot_map_fps_weapon_id ON loot_map(fps_weapon_id);
CREATE INDEX idx_loot_map_game_version ON loot_map(game_version_id);
CREATE INDEX idx_loot_map_harvestable  ON loot_map(harvestable_id);
CREATE INDEX idx_loot_map_props        ON loot_map(props_id);
CREATE INDEX idx_loot_map_rarity       ON loot_map(rarity);
CREATE INDEX idx_loot_map_ship_missile ON loot_map(ship_missile_id);
CREATE INDEX idx_loot_map_sub_type     ON loot_map(sub_type);
CREATE INDEX idx_loot_map_type         ON loot_map(type);
CREATE INDEX idx_loot_map_uuid_gv ON loot_map(uuid, game_version_id);
CREATE INDEX idx_loot_map_vehicle_component_id ON loot_map(vehicle_component_id);

-- Rebuild: manufacturers
DROP TABLE IF EXISTS manufacturers;
CREATE TABLE manufacturers (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid            TEXT    NOT NULL,
  name            TEXT    NOT NULL,
  slug            TEXT    NOT NULL,
  code            TEXT,
  known_for       TEXT,
  description     TEXT,
  logo_url        TEXT,
  raw_data        TEXT,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME DEFAULT CURRENT_TIMESTAMP, class TEXT, removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);

-- Rebuild: mineable_elements
DROP TABLE IF EXISTS mineable_elements;
CREATE TABLE mineable_elements (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid              TEXT    NOT NULL,
  name              TEXT    NOT NULL,
  slug              TEXT,
  class_name        TEXT,
  category          TEXT,
  commodity_id      INTEGER REFERENCES commodities(id),
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT    DEFAULT (datetime('now')),
  updated_at        TEXT    DEFAULT (datetime('now')), instability REAL, resistance REAL, optimal_window_midpoint REAL, optimal_window_randomness REAL, optimal_window_thinness REAL, explosion_multiplier REAL, cluster_factor REAL, removed INTEGER NOT NULL DEFAULT 0, [optimal_midpoint] REAL, [resource_type] TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_mineable_elements_category ON mineable_elements(category);
CREATE INDEX idx_mineable_elements_slug ON mineable_elements(slug);

-- Rebuild: mining_clustering_presets
DROP TABLE IF EXISTS mining_clustering_presets;
CREATE TABLE "mining_clustering_presets" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL,
    name TEXT NOT NULL,
    probability_of_clustering REAL NOT NULL DEFAULT 0,
    game_version_id INTEGER REFERENCES game_versions(id), removed INTEGER NOT NULL DEFAULT 0, [params] TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
    UNIQUE(uuid)
);

-- Rebuild: mission_givers
DROP TABLE IF EXISTS mission_givers;
CREATE TABLE mission_givers (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid              TEXT    NOT NULL,
  name              TEXT    NOT NULL,
  slug              TEXT,
  description       TEXT,
  faction_id        INTEGER REFERENCES factions(id),
  location_id       INTEGER REFERENCES star_map_locations(id),
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT    DEFAULT (datetime('now')),
  updated_at        TEXT    DEFAULT (datetime('now')), removed INTEGER NOT NULL DEFAULT 0, biography TEXT, occupation TEXT, association TEXT, headquarters TEXT, portrait_url TEXT, is_lawful INTEGER, allies_json TEXT, enemies_json TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_mission_givers_faction ON mission_givers(faction_id);
CREATE INDEX idx_mission_givers_location ON mission_givers(location_id);
CREATE INDEX idx_mission_givers_slug ON mission_givers(slug);

-- Rebuild: mission_organizations
DROP TABLE IF EXISTS mission_organizations;
CREATE TABLE mission_organizations (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid              TEXT    NOT NULL,
  name              TEXT    NOT NULL,
  slug              TEXT,
  description       TEXT,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT    DEFAULT (datetime('now')),
  updated_at        TEXT    DEFAULT (datetime('now')), data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_mission_organizations_slug ON mission_organizations(slug);

-- Rebuild: mission_prerequisites
DROP TABLE IF EXISTS mission_prerequisites;
CREATE TABLE mission_prerequisites (
  mission_id INTEGER NOT NULL REFERENCES missions(id),
  required_mission_id INTEGER NOT NULL REFERENCES missions(id),
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id), data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  PRIMARY KEY (mission_id, required_mission_id)
);
CREATE INDEX idx_mp_required ON mission_prerequisites(required_mission_id);

-- Rebuild: mission_types
DROP TABLE IF EXISTS mission_types;
CREATE TABLE mission_types (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid              TEXT    NOT NULL,
  name              TEXT    NOT NULL,
  slug              TEXT,
  description       TEXT,
  category          TEXT,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT    DEFAULT (datetime('now')),
  updated_at        TEXT    DEFAULT (datetime('now')), removed INTEGER NOT NULL DEFAULT 0, [icon_name] TEXT, [svg_icon_path] TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_mission_types_category ON mission_types(category);

-- Rebuild: missions
DROP TABLE IF EXISTS missions;
CREATE TABLE missions (
  id                    INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid                  TEXT NOT NULL,
  title                 TEXT,
  display_name          TEXT,
  description           TEXT,
  mission_type_id       INTEGER REFERENCES mission_types(id),
  mission_giver_id      INTEGER REFERENCES mission_givers(id),
  reward_amount         INTEGER DEFAULT 0,
  reward_currency       TEXT DEFAULT 'aUEC',
  reputation_scope_id   INTEGER REFERENCES reputation_scopes(id),
  reputation_reward_size TEXT,
  min_reputation        INTEGER,
  is_lawful             INTEGER,
  not_for_release       INTEGER DEFAULT 0,
  location_hint         TEXT,
  category              TEXT,
  subcategory           TEXT,
  difficulty            TEXT,
  game_version_id       INTEGER NOT NULL REFERENCES game_versions(id), removed INTEGER NOT NULL DEFAULT 0, rep_fail_summary TEXT, rep_abandon_summary TEXT, time_limit_minutes INTEGER, max_players INTEGER, can_share INTEGER DEFAULT 1, once_only INTEGER DEFAULT 0, fail_if_criminal INTEGER, available_in_prison INTEGER DEFAULT 0, wanted_level_min INTEGER DEFAULT 0, wanted_level_max INTEGER DEFAULT 5, buy_in_amount INTEGER DEFAULT 0, reward_max INTEGER, has_standing_bonus INTEGER DEFAULT 0, location_ref TEXT, locality TEXT, [lawful] INTEGER, [mission_giver] TEXT, [mission_type] TEXT, [name] TEXT, [reward_min] INTEGER, [slug] TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_missions_category ON missions(category);
CREATE INDEX idx_missions_giver ON missions(mission_giver_id);
CREATE INDEX idx_missions_reputation ON missions(reputation_scope_id);
CREATE INDEX idx_missions_type ON missions(mission_type_id);
CREATE INDEX idx_missions_version ON missions(game_version_id);

-- Rebuild: npc_loadouts
DROP TABLE IF EXISTS npc_loadouts;
CREATE TABLE npc_loadouts (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  file_path         TEXT NOT NULL,
  loadout_name      TEXT NOT NULL,
  faction_id        INTEGER REFERENCES npc_factions(id),
  category          TEXT NOT NULL,
  sub_category      TEXT,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT DEFAULT (datetime('now')), visible_item_count INTEGER DEFAULT 0, removed INTEGER NOT NULL DEFAULT 0, [faction] TEXT, [item_count] INTEGER, [name] TEXT, [species] TEXT, [uuid] TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(file_path)
);
CREATE INDEX idx_npc_loadouts_faction ON npc_loadouts(faction_id);
CREATE INDEX idx_npc_loadouts_version ON npc_loadouts(game_version_id);

-- Rebuild: paints
DROP TABLE IF EXISTS paints;
CREATE TABLE "paints" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid TEXT,
    name TEXT NOT NULL,
    slug TEXT,
    class_name TEXT,
    description TEXT,
    image_url TEXT,
    image_url_small TEXT,
    image_url_medium TEXT,
    image_url_large TEXT,
    raw_data TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    is_base_variant INTEGER DEFAULT 0,
    game_version_id INTEGER REFERENCES game_versions(id), [can_loot] INTEGER, [grade] INTEGER, [grid_height] INTEGER, [grid_width] INTEGER, [inventory_volume] REAL, [loot_rarity] TEXT, [manufacturer_code] TEXT, [size] INTEGER, [sub_type] TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
    UNIQUE(class_name)
);
CREATE INDEX idx_paints_class_name ON paints(class_name);
CREATE INDEX idx_paints_slug ON paints(slug);
CREATE INDEX idx_paints_version ON paints(game_version_id);

-- Rebuild: props
DROP TABLE IF EXISTS props;
CREATE TABLE props (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid            TEXT    NOT NULL,
  class_name      TEXT    NOT NULL,
  name            TEXT    NOT NULL,
  slug            TEXT,
  description     TEXT,
  type            TEXT,
  sub_type        TEXT,
  manufacturer_id INTEGER REFERENCES manufacturers(id),
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  created_at      TEXT    DEFAULT (datetime('now')),
  updated_at      TEXT    DEFAULT (datetime('now')), removed INTEGER NOT NULL DEFAULT 0, [manufacturer_code] TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_props_slug     ON props(slug);
CREATE INDEX idx_props_sub_type ON props(sub_type);

-- Rebuild: refining_processes
DROP TABLE IF EXISTS refining_processes;
CREATE TABLE refining_processes (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid              TEXT    NOT NULL,
  name              TEXT    NOT NULL,
  slug              TEXT,
  speed             TEXT    NOT NULL,
  quality           TEXT    NOT NULL,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT    DEFAULT (datetime('now')),
  updated_at        TEXT    DEFAULT (datetime('now')), removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);

-- Rebuild: reputation_perks
DROP TABLE IF EXISTS reputation_perks;
CREATE TABLE reputation_perks (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  scope_id          INTEGER NOT NULL REFERENCES reputation_scopes(id),
  standing_id       INTEGER NOT NULL REFERENCES reputation_standings(id),
  perk_name         TEXT NOT NULL,
  display_name      TEXT,
  description       TEXT,
  reward_item_uuid  TEXT,
  reward_item_name  TEXT,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id), removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(scope_id, standing_id, perk_name)
);
CREATE INDEX idx_reputation_perks_scope ON reputation_perks(scope_id);
CREATE INDEX idx_reputation_perks_version ON reputation_perks(game_version_id);

-- Rebuild: reputation_reward_tiers
DROP TABLE IF EXISTS reputation_reward_tiers;
CREATE TABLE reputation_reward_tiers (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  size_code       TEXT NOT NULL,
  direction       TEXT NOT NULL,
  rep_amount      INTEGER NOT NULL,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id), removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(size_code, direction)
);
CREATE INDEX idx_reputation_reward_tiers_version ON reputation_reward_tiers(game_version_id);

-- Rebuild: reputation_scopes
DROP TABLE IF EXISTS reputation_scopes;
CREATE TABLE reputation_scopes (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid              TEXT    NOT NULL,
  name              TEXT    NOT NULL,
  slug              TEXT,
  scope_key         TEXT    NOT NULL,
  description       TEXT,
  faction_id        INTEGER REFERENCES factions(id),
  max_reputation    INTEGER,
  initial_reputation INTEGER DEFAULT 0,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT    DEFAULT (datetime('now')),
  updated_at        TEXT    DEFAULT (datetime('now')), removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_reputation_scopes_key ON reputation_scopes(scope_key);

-- Rebuild: reputation_standings
DROP TABLE IF EXISTS reputation_standings;
CREATE TABLE "reputation_standings" (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid              TEXT    NOT NULL,
  name              TEXT    NOT NULL,
  slug              TEXT,
  scope_id          INTEGER NOT NULL REFERENCES reputation_scopes(id),
  min_reputation    INTEGER NOT NULL,
  drift_reputation  INTEGER DEFAULT 0,
  drift_time_hours  REAL    DEFAULT 0,
  is_gated          INTEGER DEFAULT 0,
  perk_description  TEXT,
  sort_order        INTEGER,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT    DEFAULT (datetime('now')),
  updated_at        TEXT    DEFAULT (datetime('now')), removed INTEGER NOT NULL DEFAULT 0, [description] TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid, scope_id)
);
CREATE INDEX idx_reputation_standings_scope ON reputation_standings(scope_id);

-- Rebuild: rock_compositions
DROP TABLE IF EXISTS rock_compositions;
CREATE TABLE rock_compositions (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid              TEXT    NOT NULL,
  name              TEXT    NOT NULL,
  slug              TEXT,
  class_name        TEXT,
  rock_type         TEXT,
  min_elements      INTEGER,
  composition_json  TEXT,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT    DEFAULT (datetime('now')),
  updated_at        TEXT    DEFAULT (datetime('now')), removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_rock_compositions_rock_type ON rock_compositions(rock_type);

-- Index rebuild: salvageable_ships
DROP INDEX IF EXISTS idx_salvageable_ships_uuid_version;
CREATE UNIQUE INDEX idx_salvageable_ships_uuid_version ON salvageable_ships(entity_uuid);

-- Rebuild: ship_missiles
DROP TABLE IF EXISTS ship_missiles;
CREATE TABLE ship_missiles (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid            TEXT    NOT NULL,
  class_name      TEXT,
  name            TEXT    NOT NULL,
  slug            TEXT,
  description     TEXT,
  type            TEXT,
  sub_type        TEXT,
  size            INTEGER,
  grade           TEXT,
  manufacturer_id INTEGER REFERENCES manufacturers(id),
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  created_at      TEXT    DEFAULT (datetime('now')),
  updated_at      TEXT    DEFAULT (datetime('now')), missile_type TEXT, lock_time REAL, tracking_signal TEXT, damage REAL, damage_type TEXT, blast_radius REAL, speed REAL, lock_range REAL, ammo_count INTEGER, removed INTEGER NOT NULL DEFAULT 0, [manufacturer_code] TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_ship_missiles_size ON ship_missiles(size);
CREATE INDEX idx_ship_missiles_type ON ship_missiles(type, sub_type);
CREATE INDEX idx_ship_missiles_uuid ON ship_missiles(uuid);

-- Rebuild: shop_franchises
DROP TABLE IF EXISTS shop_franchises;
CREATE TABLE "shop_franchises" (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid              TEXT    NOT NULL,
  name              TEXT    NOT NULL,
  localization_key  TEXT,
  slug              TEXT,
  game_version_id   INTEGER REFERENCES game_versions(id), data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);

-- Rebuild: shop_locations
DROP TABLE IF EXISTS shop_locations;
CREATE TABLE shop_locations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  shop_id INTEGER NOT NULL REFERENCES shops(id),
  location_id INTEGER NOT NULL REFERENCES star_map_locations(id),
  placement_name TEXT,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id), data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(shop_id, location_id)
);
CREATE INDEX idx_shop_locations_location ON shop_locations(location_id);
CREATE INDEX idx_shop_locations_shop ON shop_locations(shop_id);

-- Rebuild: shops
DROP TABLE IF EXISTS shops;
CREATE TABLE shops (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid              TEXT    NOT NULL,
  name              TEXT    NOT NULL,
  slug              TEXT,
  shop_type         TEXT,
  location_id       INTEGER REFERENCES star_map_locations(id),
  is_event          INTEGER DEFAULT 0,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT    DEFAULT (datetime('now')),
  updated_at        TEXT    DEFAULT (datetime('now')), location_label TEXT, franchise_uuid TEXT, display_name TEXT, inventory_type TEXT, removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_shops_display_name ON shops(display_name);
CREATE INDEX idx_shops_franchise ON shops(franchise_uuid);
CREATE INDEX idx_shops_location ON shops(location_id);
CREATE INDEX idx_shops_slug ON shops(slug);
CREATE INDEX idx_shops_type ON shops(shop_type);

-- Rebuild: star_map_locations
DROP TABLE IF EXISTS star_map_locations;
CREATE TABLE star_map_locations (
  id                    INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid                  TEXT    NOT NULL,
  name                  TEXT    NOT NULL,
  slug                  TEXT,
  description           TEXT,
  location_type         TEXT    NOT NULL,
  nav_icon              TEXT,
  parent_uuid           TEXT,
  star_system_id        INTEGER REFERENCES star_systems(id),
  jurisdiction_id       INTEGER REFERENCES law_jurisdictions(id),
  size_meters           REAL,
  qt_obstruction_radius REAL,
  qt_arrival_radius     REAL,
  qt_adoption_radius    REAL,
  respawn_type          TEXT,
  is_scannable          INTEGER DEFAULT 0,
  hide_in_starmap       INTEGER DEFAULT 0,
  amenities_json        TEXT,
  game_version_id       INTEGER NOT NULL REFERENCES game_versions(id),
  created_at            TEXT    DEFAULT (datetime('now')),
  updated_at            TEXT    DEFAULT (datetime('now')), removed INTEGER NOT NULL DEFAULT 0, [affiliation] TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_star_map_locations_jurisdiction ON star_map_locations(jurisdiction_id);
CREATE INDEX idx_star_map_locations_parent ON star_map_locations(parent_uuid);
CREATE INDEX idx_star_map_locations_slug ON star_map_locations(slug);
CREATE INDEX idx_star_map_locations_system ON star_map_locations(star_system_id);
CREATE INDEX idx_star_map_locations_type ON star_map_locations(location_type);

-- Rebuild: star_systems
DROP TABLE IF EXISTS star_systems;
CREATE TABLE star_systems (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid              TEXT    NOT NULL,
  name              TEXT    NOT NULL,
  slug              TEXT,
  code              TEXT,
  description       TEXT,
  galactic_x        REAL,
  galactic_y        REAL,
  galactic_z        REAL,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  created_at        TEXT    DEFAULT (datetime('now')),
  updated_at        TEXT    DEFAULT (datetime('now')), removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);

-- Rebuild: terminal_inventory
DROP TABLE IF EXISTS terminal_inventory;
CREATE TABLE terminal_inventory (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  terminal_id INTEGER NOT NULL REFERENCES terminals(id),
  item_uuid TEXT NOT NULL,
  item_type TEXT,
  item_name TEXT,
  base_buy_price REAL,
  base_sell_price REAL,
  latest_buy_price REAL,
  latest_sell_price REAL,
  latest_source TEXT,
  latest_observed_at TEXT,
  base_inventory REAL,
  max_inventory REAL,
  game_version_id INTEGER REFERENCES game_versions(id),
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')), is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(terminal_id, item_uuid)
);
CREATE INDEX idx_terminal_inventory_item ON terminal_inventory(item_uuid);
CREATE INDEX idx_terminal_inventory_terminal ON terminal_inventory(terminal_id);

-- Rebuild: trade_commodities
DROP TABLE IF EXISTS trade_commodities;
CREATE TABLE trade_commodities (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid            TEXT NOT NULL,
    name            TEXT NOT NULL,
    slug            TEXT NOT NULL,
    class_name      TEXT,
    category        TEXT,        -- Directory category: metals, minerals, gas, vice, food, etc.
    type_name       TEXT,        -- Commodity type: Metal, Gas, Mineral, etc.
    subtype_name    TEXT,        -- Commodity subtype: Agricium, Hydrogen, etc.
    is_raw          INTEGER DEFAULT 0,  -- 1 = unrefined/ore form
    boxable         INTEGER DEFAULT 0,  -- 1 = can be boxed as physical commodity
    scu_per_unit    REAL,        -- SCU occupancy per unit (from centiSCU / 100)
    description     TEXT,
    game_version_id INTEGER REFERENCES game_versions(id),
    created_at      TEXT DEFAULT (datetime('now')),
    updated_at      TEXT DEFAULT (datetime('now')), removed INTEGER NOT NULL DEFAULT 0, [sub_category] TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
    UNIQUE(uuid)
);
CREATE INDEX idx_trade_commodities_category ON trade_commodities(category);
CREATE INDEX idx_trade_commodities_slug ON trade_commodities(slug);

-- Rebuild: vehicle_careers
DROP TABLE IF EXISTS vehicle_careers;
CREATE TABLE vehicle_careers (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid            TEXT    NOT NULL,
  name            TEXT    NOT NULL,
  slug            TEXT,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id), removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);

-- Rebuild: vehicle_components
DROP TABLE IF EXISTS vehicle_components;
CREATE TABLE "vehicle_components" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT NOT NULL,
  name TEXT NOT NULL,
  slug TEXT,
  class_name TEXT,
  manufacturer_id INTEGER,
  type TEXT NOT NULL,
  sub_type TEXT,
  size INTEGER,
  grade TEXT,
  description TEXT,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  raw_data TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  class TEXT,
  component_class TEXT,
  em_signature REAL,
  mass REAL,
  hp REAL,
  power_draw REAL,
  power_draw_min REAL,
  thermal_output REAL,
  base_heat_generation REAL,
  distortion_max REAL,
  removed INTEGER NOT NULL DEFAULT 0,
  manufacturer_code TEXT,
  can_loot INTEGER,
  loot_rarity TEXT,
  inventory_volume REAL,
  grid_width INTEGER,
  grid_height INTEGER,
  capacity REAL,
  data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);

-- Rebuild: vehicle_modules
DROP TABLE IF EXISTS vehicle_modules;
CREATE TABLE vehicle_modules (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid            TEXT    NOT NULL,
  vehicle_id      INTEGER NOT NULL REFERENCES vehicles(id),
  port_name       TEXT    NOT NULL,
  class_name      TEXT    NOT NULL,
  display_name    TEXT,
  size            INTEGER,
  tags            TEXT,
  is_default      INTEGER NOT NULL DEFAULT 0,
  has_loadout     INTEGER NOT NULL DEFAULT 0,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id),
  created_at      TEXT    DEFAULT (datetime('now')),
  removed         INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid, vehicle_id)
);
CREATE INDEX idx_vehicle_modules_port ON vehicle_modules(vehicle_id, port_name);
CREATE INDEX idx_vehicle_modules_vehicle ON vehicle_modules(vehicle_id);
CREATE INDEX idx_vehicle_modules_version ON vehicle_modules(game_version_id);

-- Rebuild: vehicle_ports
DROP TABLE IF EXISTS vehicle_ports;
CREATE TABLE vehicle_ports (
  id                 INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid               TEXT    NOT NULL,
  vehicle_id         INTEGER NOT NULL REFERENCES vehicles(id),
  parent_port_id     INTEGER REFERENCES vehicle_ports(id),
  name               TEXT    NOT NULL,
  position           TEXT,
  category_label     TEXT,
  size_min           INTEGER,
  size_max           INTEGER,
  port_type          TEXT,
  port_subtype       TEXT,
  equipped_item_uuid TEXT,
  editable           BOOLEAN DEFAULT TRUE,
  health             REAL,
  game_version_id    INTEGER NOT NULL REFERENCES game_versions(id),
  created_at         DATETIME DEFAULT CURRENT_TIMESTAMP, controller TEXT, controller_label TEXT, missile_type TEXT, removed INTEGER NOT NULL DEFAULT 0, [max_size] INTEGER, [min_size] INTEGER, [parent_port_name] TEXT, [port_name] TEXT, [vehicle_name] TEXT, [vehicle_uuid] TEXT, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);
CREATE INDEX idx_vehicle_ports_controller ON vehicle_ports(controller);
CREATE INDEX idx_vehicle_ports_parent_port_id ON vehicle_ports(parent_port_id);
CREATE INDEX idx_vehicle_ports_vehicle_id    ON vehicle_ports(vehicle_id);

-- Rebuild: vehicle_roles
DROP TABLE IF EXISTS vehicle_roles;
CREATE TABLE vehicle_roles (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid            TEXT    NOT NULL,
  name            TEXT    NOT NULL,
  slug            TEXT,
  game_version_id INTEGER NOT NULL REFERENCES game_versions(id), removed INTEGER NOT NULL DEFAULT 0, data_source TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid)
);

-- Rebuild: vehicle_suit_lockers
DROP TABLE IF EXISTS vehicle_suit_lockers;
CREATE TABLE vehicle_suit_lockers (
  id                 INTEGER PRIMARY KEY AUTOINCREMENT,
  vehicle_id         INTEGER REFERENCES vehicles(id),
  locker_entity_name TEXT NOT NULL,
  uuid               TEXT NOT NULL,
  locker_label       TEXT,
  locker_count       INTEGER DEFAULT 1,
  game_version_id    INTEGER NOT NULL REFERENCES game_versions(id),
  removed            INTEGER NOT NULL DEFAULT 0,
  vehicle_name       TEXT,
  data_source        TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid, vehicle_id)
);
CREATE INDEX idx_vehicle_suit_lockers_vehicle ON vehicle_suit_lockers(vehicle_id);
CREATE INDEX idx_vehicle_suit_lockers_version ON vehicle_suit_lockers(game_version_id);

-- Rebuild: vehicle_weapon_racks
DROP TABLE IF EXISTS vehicle_weapon_racks;
CREATE TABLE vehicle_weapon_racks (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  vehicle_id        INTEGER REFERENCES vehicles(id),
  rack_entity_name  TEXT NOT NULL,
  uuid              TEXT NOT NULL,
  rack_label        TEXT,
  total_ports       INTEGER NOT NULL DEFAULT 0,
  rifle_ports       INTEGER NOT NULL DEFAULT 0,
  pistol_ports      INTEGER NOT NULL DEFAULT 0,
  heavy_ports       INTEGER NOT NULL DEFAULT 0,
  utility_ports     INTEGER NOT NULL DEFAULT 0,
  min_size          INTEGER,
  max_size          INTEGER,
  game_version_id   INTEGER NOT NULL REFERENCES game_versions(id),
  removed           INTEGER NOT NULL DEFAULT 0,
  vehicle_name      TEXT,
  entity_name       TEXT,
  port_name         TEXT,
  rack_type         TEXT,
  data_source       TEXT, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT,
  UNIQUE(uuid, vehicle_id)
);
CREATE INDEX idx_vehicle_weapon_racks_vehicle ON vehicle_weapon_racks(vehicle_id);
CREATE INDEX idx_vehicle_weapon_racks_version ON vehicle_weapon_racks(game_version_id);

-- Rebuild: vehicles
DROP TABLE IF EXISTS vehicles;
CREATE TABLE vehicles (
  id                        INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid                      TEXT,
  slug                      TEXT    NOT NULL,
  name                      TEXT    NOT NULL,
  class_name                TEXT,
  manufacturer_id           INTEGER REFERENCES manufacturers(id),
  vehicle_type_id           INTEGER REFERENCES vehicle_types(id),
  production_status_id      INTEGER REFERENCES production_statuses(id),
  size                      INTEGER,
  size_label                TEXT,
  focus                     TEXT,
  classification            TEXT,
  description               TEXT,
  length                    REAL,
  beam                      REAL,
  height                    REAL,
  mass                      REAL,
  cargo                     REAL,
  vehicle_inventory         REAL,
  crew_min                  INTEGER,
  crew_max                  INTEGER,
  speed_scm                 REAL,
  speed_max                 REAL,
  health                    REAL,
  pledge_price              REAL,
  price_auec                REAL,
  on_sale                   BOOLEAN DEFAULT FALSE,
  image_url                 TEXT,
  image_url_small           TEXT,
  image_url_medium          TEXT,
  image_url_large           TEXT,
  pledge_url                TEXT,
  game_version_id           INTEGER NOT NULL REFERENCES game_versions(id),
  raw_data                  TEXT,
  created_at                DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at                DATETIME DEFAULT CURRENT_TIMESTAMP,
  parent_vehicle_id         INTEGER REFERENCES vehicles(id),
  is_paint_variant          INTEGER NOT NULL DEFAULT 0,
  boost_speed_back          INTEGER,
  angular_velocity_pitch    REAL,
  angular_velocity_yaw      REAL,
  angular_velocity_roll     REAL,
  fuel_capacity_hydrogen    REAL,
  fuel_capacity_quantum     REAL,
  thruster_count_main       INTEGER,
  thruster_count_maneuvering INTEGER,
  acquisition_type          TEXT, acquisition_source_name TEXT, cross_section_x REAL, cross_section_y REAL, cross_section_z REAL, ir_signature REAL, em_signature REAL, removed INTEGER NOT NULL DEFAULT 0, armor_hp INTEGER DEFAULT 0, armor_damage_physical REAL DEFAULT 1, armor_damage_energy REAL DEFAULT 1, armor_damage_distortion REAL DEFAULT 1, armor_damage_thermal REAL DEFAULT 1, armor_deflection_physical REAL DEFAULT 0, armor_deflection_energy REAL DEFAULT 0, armor_signal_ir REAL DEFAULT 1, armor_signal_em REAL DEFAULT 1, armor_signal_cs REAL DEFAULT 1, weapon_pool_size INTEGER DEFAULT 0, shield_pool_max INTEGER DEFAULT 0, replaced_by_vehicle_id INTEGER REFERENCES vehicles(id), [manufacturer_code] TEXT, [vehicle_type] TEXT, data_source TEXT, claim_time REAL, expedited_claim_time REAL, expedited_claim_cost INTEGER, is_pledgeable INTEGER NOT NULL DEFAULT 1, is_deleted INTEGER DEFAULT 0, deleted_at TEXT, deleted_in_patch TEXT, short_slug TEXT,
  UNIQUE(slug)
);
CREATE INDEX idx_vehicles_is_pledgeable ON vehicles(is_pledgeable)
  WHERE is_pledgeable = 0;
CREATE INDEX idx_vehicles_manufacturer_id ON vehicles(manufacturer_id);

PRAGMA foreign_keys = ON;

-- Summary: 71 tables rebuilt, 3 index-only, 0 skipped