"""Unit tests for the SQL row-write estimator in scripts/d1-budget.py.

Run with: python3 -m unittest scripts.test_d1_budget
"""
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

# Import the script as a module. It has a hyphen in the filename so use importlib.
import importlib.util
spec = importlib.util.spec_from_file_location("d1_budget", Path(__file__).parent / "d1-budget.py")
d1_budget = importlib.util.module_from_spec(spec)
spec.loader.exec_module(d1_budget)


class TestStripComments(unittest.TestCase):
    def test_line_comments(self):
        sql = "INSERT INTO t VALUES (1); -- comment\nINSERT INTO t VALUES (2);"
        out = d1_budget.strip_sql_comments(sql)
        self.assertNotIn("comment", out)

    def test_block_comments(self):
        sql = "/* header\nspanning lines */ INSERT INTO t VALUES (1);"
        out = d1_budget.strip_sql_comments(sql)
        self.assertNotIn("header", out)


class TestSplitStatements(unittest.TestCase):
    def test_basic_split(self):
        sql = "INSERT INTO a VALUES (1); INSERT INTO b VALUES (2);"
        stmts = d1_budget.split_statements(sql)
        self.assertEqual(len(stmts), 2)

    def test_semicolon_inside_string_not_split(self):
        sql = "INSERT INTO t VALUES ('a;b'); INSERT INTO t VALUES ('c');"
        stmts = d1_budget.split_statements(sql)
        self.assertEqual(len(stmts), 2)

    def test_escaped_quote_in_string(self):
        sql = "INSERT INTO t VALUES ('it''s; ok'); SELECT 1;"
        stmts = d1_budget.split_statements(sql)
        self.assertEqual(len(stmts), 2)


class TestCountValueTuples(unittest.TestCase):
    def test_single_tuple(self):
        stmt = "INSERT INTO t (a, b) VALUES (1, 2)"
        self.assertEqual(d1_budget.count_value_tuples(stmt), 1)

    def test_multi_tuple(self):
        stmt = "INSERT INTO t (a, b) VALUES (1, 2), (3, 4), (5, 6)"
        self.assertEqual(d1_budget.count_value_tuples(stmt), 3)

    def test_subquery_in_tuple_not_counted(self):
        # The pattern v2 pipeline emits — embedded subquery for FK lookup.
        stmt = (
            "INSERT INTO vehicles (id, mfr_id) "
            "VALUES (1, (SELECT id FROM mfr WHERE code='X'))"
        )
        self.assertEqual(d1_budget.count_value_tuples(stmt), 1)

    def test_on_conflict_not_counted_as_tuple(self):
        # The bug we hit: ON CONFLICT (cols) was counted as a tuple.
        stmt = (
            "INSERT INTO t (a, b) VALUES (1, 2) "
            "ON CONFLICT (a) DO UPDATE SET b = excluded.b"
        )
        self.assertEqual(d1_budget.count_value_tuples(stmt), 1)

    def test_multi_row_with_on_conflict(self):
        stmt = (
            "INSERT INTO t (a, b) VALUES (1, 2), (3, 4), (5, 6) "
            "ON CONFLICT (a) DO UPDATE SET b = excluded.b"
        )
        self.assertEqual(d1_budget.count_value_tuples(stmt), 3)


class TestClassify(unittest.TestCase):
    def test_ddl_zero_rows(self):
        for ddl in [
            "CREATE TABLE t (id INTEGER)",
            "DROP TABLE IF EXISTS t",
            "ALTER TABLE t ADD COLUMN c TEXT",
            "PRAGMA foreign_keys = ON",
        ]:
            kind, rows, _ = d1_budget.classify_statement(ddl)
            self.assertEqual(kind, "DDL_OTHER", ddl)
            self.assertEqual(rows, 0, ddl)

    def test_insert_select_unknown(self):
        kind, rows, note = d1_budget.classify_statement(
            "INSERT INTO a SELECT * FROM b"
        )
        self.assertEqual(kind, "INSERT_SELECT")
        self.assertEqual(rows, 0)
        self.assertIn("unknown", note.lower())

    def test_delete_at_least_one(self):
        kind, rows, _ = d1_budget.classify_statement("DELETE FROM t WHERE id = 1")
        self.assertEqual(kind, "DELETE")
        self.assertEqual(rows, 1)


class TestEstimateSqlWrites(unittest.TestCase):
    def test_realistic_v2_pipeline_pattern(self):
        # Two INSERT...VALUES with embedded subquery + ON CONFLICT.
        sql = """
        -- generated by pipeline
        INSERT INTO vehicles (id, mfr_id) VALUES (1, (SELECT id FROM mfr WHERE code='X'))
            ON CONFLICT (id) DO UPDATE SET mfr_id = excluded.mfr_id;
        INSERT INTO vehicles (id, mfr_id) VALUES (2, (SELECT id FROM mfr WHERE code='Y'))
            ON CONFLICT (id) DO UPDATE SET mfr_id = excluded.mfr_id;
        """
        result = d1_budget.estimate_sql_writes(sql)
        self.assertEqual(result["statements"], 2)
        self.assertEqual(result["counts"]["INSERT_VALUES"], 2)
        self.assertEqual(result["rows"], 2)

    def test_ddl_does_not_inflate(self):
        sql = "DROP TABLE IF EXISTS t; CREATE TABLE t (id INTEGER); INSERT INTO t VALUES (1);"
        result = d1_budget.estimate_sql_writes(sql)
        self.assertEqual(result["counts"]["DDL_OTHER"], 2)
        self.assertEqual(result["rows"], 1)

    def test_billing_period_normal_case(self):
        # Imported indirectly to ensure no syntax errors. Not testing date logic
        # here — that depends on the system clock.
        from datetime import date
        # Just confirm the function exists and returns 2 strings.
        s, u = d1_budget.billing_period(2)
        self.assertRegex(s, r"\d{4}-\d{2}-\d{2}")
        self.assertRegex(u, r"\d{4}-\d{2}-\d{2}")


if __name__ == "__main__":
    unittest.main()
